Add docker
oven077/java-shareit pull request #6
Opened 2023-01-21 19:16 UTC by oven077

blablabla

2023-01-22 10:43 UTC, andrew-larkin requested changes
Привет! Написал комментарии в некоторых местах - они актуальны для всех остальных классов, изменения точно требуются для всех сервисов. Еще если запустить тесты разом, 8 из них падают, надо проверить. а в остальном все в порядке, внести правки и приложение будет полностью готово.

2023-01-22 10:43 UTC, andrew-larkin commented on docker-compose.yml
> +#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
закомментированный код в этом файле нужно удалить

2023-01-22 10:43 UTC, andrew-larkin commented on gateway/src/main/java/ru/practicum/shareit/item/CommentDto.java
> +    //    private User author;
закомментированный код нужно удалить во всех файлах

2023-01-22 10:43 UTC, andrew-larkin commented on gateway/src/main/resources/application.properties
> +#logging.level.httpclient.wire=DEBUG
удалить

2023-01-22 10:43 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                                             @Positive @RequestParam(value = "size", defaultValue = "10") int pageSize) {
во всех контроллерах нужно примитивные аргументы переделать на врапперы (int->Integer), т.к. нам могут понадобиться свойства класса Object для работы с ними

2023-01-22 10:43 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/booking/dao/BookingRepository.java
> +
нужно добавить @Repository

2023-01-22 10:43 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> + * TODO Sprint add-bookings.
todo тоже можно везде убрать

2023-01-22 10:43 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        Boolean isAvailable;
это не зачем - разделять объявление и инициализацию. везде где встречается подобное, нужно сделать чтобы они шли как  Boolean isAvailable = item.getAvailable();

2023-01-22 10:43 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        Booking booking;
здесь тоже. такая ситуация, когда метод на 113 строке срабатывает напрасно - такого не должно быть

2023-01-22 10:43 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/item/comment/Comment.java
> +
лишние пробелы тоже стоит убрать

2023-01-22 10:43 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/item/comment/CommentRepository.java
> +
@Repository

2023-01-22 10:43 UTC, andrew-larkin commented on server/src/test/java/ru/practicum/shareit/ShareItTests.java
> +    @Test
8 тестов падают с ошибкой, если запустить тесты одновременно

2023-01-22 17:07 UTC, andrew-larkin requested changes
Привет! Необходимо еще внести правки, не во всех местах поправил первый раз.

2023-01-22 17:07 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +@Component
аннотация @Service вместо компонента

2023-01-22 17:07 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +
лишние пробелы удалить

2023-01-22 17:07 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        int itemId;
повисшее объявление переменной - такого быть не должно

2023-01-22 17:07 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        bookingRepository.findById(bookingId).orElseThrow(() -> new NotFoundException("Not found booking with id: " + bookingId));
это строка должна быть объединена со строкой 113

2023-01-22 17:07 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        User booker;
повисшее объявление переменной

2023-01-22 17:07 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        userRepository.findById(userId).orElseThrow(() -> new NotFoundException("Not found booking with id: " + userId));
объединить строки 140 и 141 и User booker объявление добавить сюда же

2023-01-22 17:07 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        User owner;
такая же ситуация

2023-01-22 17:07 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/item/dao/ItemRepository.java
> +@Transactional
она здесь не нужна

2023-01-22 17:07 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +@Component
аннотация @Service вместо @Component

2023-01-22 17:07 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +        Item newItem;
повисшая переменная

2023-01-22 17:07 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +//    @GeneratedValue(strategy = GenerationType.IDENTITY)
удалить закомментированный код

2023-01-22 17:07 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/request/service/ItemRequestService.java
> +        ItemRequest itemRequest;
повисшая переменная

2023-01-22 17:07 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/user/dao/UserRepository.java
> +@Component
@Repository

2023-01-22 17:07 UTC, andrew-larkin commented on server/src/main/java/ru/practicum/shareit/user/service/UserService.java
> +@Component
@Service

2023-01-22 17:07 UTC, andrew-larkin commented on server/src/test/java/ru/practicum/shareit/booking/controller/BookingControllerTest.java
> +
задизэйбленные тесты удалить или поправить

2023-01-23 12:55 UTC, oven077 commented
все тесты пройдены! лютый голвоняк

2023-02-03 12:42 UTC, merged